#! /bin/bash


sudo modprobe bcm2835-v4l2
stty -F /dev/ttyACM0 9600
#python serialcmd.py
#cd /home/pi/LaneRecog_PI_CntrlIntl_V18/
#cd /home/pi/LaneRecog_PI_CntrlIntl_V20/
cd /home/pi/LaneRecog_PI_CntrlIntl_V21/
#python serialcmd-onestep.py
./LaneRecog

#while [[ -z "$INPUT" ]]
#do
#	read -s -p "enter" INPUT
#done
